### ISSUE TITLE
UIのTime表記について

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#10]
StoryboardのTime表記ですが、添付した画像のように、
時間入力の際にNaNではなく[00:00:00] mm:ss:msec の用に表記できるとユーザーにも分かりやすいかと思います。

またStoryboard側のTimeも

Cut
00:00:00
１行あける
Total
00:00:00

と表示するとかなり見やすいと感じました。
修正出来そうであれば宜しくお願いします。

![UI_01](https://user-images.githubusercontent.com/47027471/71873014-70116b80-3161-11ea-9d54-81ce62e15949.jpg)

![UI_02](https://user-images.githubusercontent.com/47027471/71873231-0cd40900-3162-11ea-9128-2022a137e576.jpg)

**Comment by usk-fujikawa** [comment]
Cut数についても
cut xxxの[cut]の表示は無しにして、
数字のみの表記でよいかもしれません。


<img width="276" alt="スクリーンショット 2020-01-07 16 38 18" src="https://user-images.githubusercontent.com/47027471/71877299-211d0380-316c-11ea-93b1-a2f6aa9eaaee.png">

**Comment by usk-fujikawa** [comment]
Cut Noが000 から振られるようになっていますが、
001から始まったほうが、使っていて分かりやすい気がしました。

**Comment by kwiksher** [comment]
Cut Noも 001から始まるようにしました。

**Comment by usk-fujikawa** [comment]
Cut Noも 001から始まることを確認
