### ISSUE TITLE
Bug:storyboard-importerがインストールされない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#14]
別のPCに新規でStoryboard Plugin Managerでプラングインをインストールを完了し、XDでは動作したが
Prのstoryboard-importerがメニューにも表示されず、

~/Library/Application Support/Adobe/

配下のCEP/以下に何もインスールされていない

**Comment by kwiksher** [comment]
mkdir -p を入れてみました。これでどうでしょうか？

**Comment by usk-fujikawa** [comment]
正しくインストールされることを確認しました。
