### ISSUE TITLE
Bug:AddボタンでCutを追加 - Update, autoNumbering

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#16]
Cut 000から002とデータを入力し、
追加のCutを増やそうとAddボタンを押すと、
000〜002の枠を足した高さで、追加のCut 003が作成される

<img width="921" alt="スクリーンショット 2020-01-21 21 32 40" src="https://user-images.githubusercontent.com/47027471/72805278-d89a3580-3c95-11ea-835d-10642d0378bb.png">

**Comment by kwiksher** [comment]
Fixed.  Auto Numbering すると内部では 配列の順番が逆になるため

**Comment by usk-fujikawa** [comment]
確認しましたが、[Add]ボタンを押すと、添付しました画像のように表示が崩れてしまいます。
画像を押下前後の画像を添付（再現率100%）

<img width="1792" alt="before" src="https://user-images.githubusercontent.com/47027471/74299662-c0976c80-4d90-11ea-9f45-8522f4fad56c.png">

<img width="1792" alt="after" src="https://user-images.githubusercontent.com/47027471/74299674-c9883e00-4d90-11ea-8f90-fc4c5febd155.png">

**Comment by kwiksher** [comment]
AutoNumbering がされていないためと思われます。Createしたときに自動でAutoNumberingもするように修正してみました。

**Comment by usk-fujikawa** [comment]
[AutoNumbering]や[update]ボタンをを押すと、またCut Noが降順になるようになってしまいました。

<img width="1307" alt="スクリーンショット 2020-02-12 17 08 09" src="https://user-images.githubusercontent.com/47027471/74316093-2c42ff00-4dbc-11ea-892d-688f4e475e3d.png">

**Comment by kwiksher** [comment]
xd template.xd が古いようです。XDのコンポネントでみると character がありますでしょうか？

![image](https://user-images.githubusercontent.com/4041539/74334845-147c7280-4dde-11ea-84a2-ce1e0611f8e1.png)

こちらからDLできます。xd template ﾌｧｲﾙ （CutType -> Characterに変更）

https://kwiksher.com/storyboard-editor/doc/installation/

**Comment by usk-fujikawa** [comment]
新しいテンプレートで動作確認した結果、[Add]ボタンで新しく行は追加できましたが、
追加された項目の写真はOKですが、Total timeとTextが反映されないようです。
さらに[Add]で行を追加すると全体の表示が崩れてしまいます。

<img width="2327" alt="スクリーンショット 2020-02-13 10 38 46" src="https://user-images.githubusercontent.com/47027471/74393539-c2733580-4e4d-11ea-8e8a-e5d37c8e8968.png">

[Add]ボタンで行を追加
↓

<img width="2327" alt="スクリーンショット 2020-02-13 10 39 04" src="https://user-images.githubusercontent.com/47027471/74393589-de76d700-4e4d-11ea-9459-d0bba21a4ef6.png">

さらに[Add]ボタンで行を追加
↓

<img width="2327" alt="スクリーンショット 2020-02-13 10 39 31" src="https://user-images.githubusercontent.com/47027471/74393633-f5b5c480-4e4d-11ea-8c88-40758303ecdd.png">

**Comment by kwiksher** [comment]
FIX 0.1.1 sortが抜けていたので入れました

Total timeが再現したので修正しておきましたが、Textはこちらで問題なく挿入されてました。0.1.1でもTextが反映されない問題は残っていますでしょうか？

**Comment by usk-fujikawa** [comment]
0.1.1で動作確認したところ、Total time、Text共に正く反映されることを確認しました。
