### ISSUE TITLE
Bug:Mac版で正しくインストールされない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#17]
Mac版でインストールを行うと、インスートール時に
/Users/vjusk-imac/Library/Application Support/Adobe/Adobe XD/plugins/
の配下に[storyboard-editor]のフォルダが作成されずに、
[main.js]、[manifest.json]、[assets]がplugins/の配下に置かれてしまい、
XDのPliginにstoryboard-editorが表示されない。
再現率：100%

<img width="1181" alt="スクリーンショット 2020-02-03 10 22 01" src="https://user-images.githubusercontent.com/47027471/73619132-36078c80-466f-11ea-99fa-8ece4458220c.png">

**Comment by kwiksher** [comment]
mkdir -p を入れてみました。これでどうでしょうか？

**Comment by usk-fujikawa** [comment]
正しくインストールされる事確認しました
