### ISSUE TITLE
UI アイコンについて

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#18]
先日お送りしたアイコン等も使用して頂けると嬉しいです。
またロケットの画像も分かりやすいアイコンに変更しました。

[icon.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4186597/icon.zip)

<img width="430" alt="スクリーンショット 2020-02-12 0 47 37" src="https://user-images.githubusercontent.com/47027471/74253088-f78a6580-4d31-11ea-9e0e-fe82453aced5.png">

**Comment by kwiksher** [comment]
新アイコンをいれてビルドしてみました

**Comment by usk-fujikawa** [comment]
アイコンの反映を確認しました。
