### ISSUE TITLE
要望：エクスポートの画像サイズについて

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#22]
デジハリからのフィードバックで、エクスポートした際の画像サイズやPrに読み込む際の要望がありました。

画像が640×440で書き出されるが、1280×720 or 1920×1080で出力する事はできないか。

<img width="924" alt="スクリーンショット 2020-02-20 15 03 23" src="https://user-images.githubusercontent.com/47027471/74906255-bf4eeb00-53f3-11ea-8c5d-514d460e3339.png">

Prで読み込む際にAVCHD→ 720p30 or 1080p30 をデフォルトに指定できないか。
※書き出しの設定に合わせる

<img width="850" alt="スクリーンショット 2020-02-20 15 12 31" src="https://user-images.githubusercontent.com/47027471/74906363-24a2dc00-53f4-11ea-9fc8-9d10ed47bbb1.png">

書き出しファイルのサイズが大きくなり過ぎないようなら、1920×1080がベスト

**Comment by kwiksher** [comment]
<img width="1335" alt="2020-02-21_1040" src="https://user-images.githubusercontent.com/4041539/74996357-ac412700-5496-11ea-8ed2-95db3328e033.png">

template xd ファイルのImageSizeと名付けられたコンポネントのサイズで出力してますので、このコンポネントのサイズを変更してみてください。

マニュアルの方にも書いておきます。

**Comment by usk-fujikawa** [comment]
1920×1080サイズでtemplate xd ファイルのImageSizeを修正してみました。
データは1920×1080サイズになりましたが、
XDで編集する際に、表示する位置がずれてしまいますが、修正できますでしょうか？

<img width="1663" alt="スクリーンショット 2020-02-28 15 15 48" src="https://user-images.githubusercontent.com/47027471/75515586-bf776800-5a3d-11ea-8f36-6613d98725a1.png">

1920×1080サイズのtemplateを添付します。

[storyboard_template_1080p3.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4265489/storyboard_template_1080p3.zip)

**Comment by kwiksher** [comment]
0.1.2 版 修正しました　添付は 1280x720


[storyboard_template_1280_720.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4269934/storyboard_template_1280_720.zip)

**Comment by usk-fujikawa** [comment]
こちら修正されていること確認しました。
