### ISSUE TITLE
Premiereに読み込んだテキストデータについて

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#30]
エクスポートしたテキストデータを確認していたところ、
テキストのステージサイズが720×576になっているようで、
Prの1920×1080の映像編集で上記の範囲外にテキストを移動できないようです。

こちら対応策などあるでしょうか？

<img width="792" alt="スクリーンショット 2020-04-14 16 11 32" src="https://user-images.githubusercontent.com/47027471/79196821-b4508e00-7e6b-11ea-87f6-31a2b2bb31af.png">

<img width="1091" alt="スクリーンショット 2020-04-14 16 12 04" src="https://user-images.githubusercontent.com/47027471/79196750-98e58300-7e6b-11ea-80c3-7589a76f687a.png">

エクスポートしたデータを添付します。
https://drive.google.com/file/d/1UsTrAM17KU866973Ckx1zzJ7t8NpP3M5/view?usp=sharing

また、もし可能でしたら下記の画像のように、
読み込んだ際に、テキストのフォントサイズ:100、テキスト位置：下側センター
をデフォルトにして読み込めると凄く便利かと思いました。

<img width="795" alt="スクリーンショット 2020-04-14 16 12 56" src="https://user-images.githubusercontent.com/47027471/79197136-3476f380-7e6c-11ea-96c2-21401b69a438.png">

<img width="1088" alt="スクリーンショット 2020-04-14 16 13 07" src="https://user-images.githubusercontent.com/47027471/79197149-3a6cd480-7e6c-11ea-850b-16ddd8989572.png">

**Comment by kwiksher** [comment]
下記のフォルダにある mogrtとxmlで定義されています。フォントサイズ:100、テキスト位置：下側センターにしたものを 画面1920×1080で作れば OKです。Impoterの方に画面サイズの選択があったほうが良いかと思いました。デフォルト 1920x1080 と小さいサイズのもの(720×576) 

~/Library/Application Support/Adobe/CEP/extensions/com.kwiksher.storyboard-importer.dev/host/

- Template.mogrt
- Template.xml

**Comment by usk-fujikawa** [comment]
XDのキャラクターのパラメーターを[Title]と[Telop]のコンボボックスにして、
Prに読み込んだ際に、
[Title]の場合、テキスト位置：中心
[Telop]の場合、テキスト位置：下側センター
とmogrtとxml内で定義するのは難しいでしょうか？

<img width="1644" alt="スクリーンショット 2020-04-14 18 22 30" src="https://user-images.githubusercontent.com/47027471/79209193-09959b00-7e7e-11ea-95b1-7a3b2bf06d82.png">

**Comment by kwiksher** [comment]
今週中にやってみます。

コンボボックスまたはリストボックスにして デフォルトのキャラクターのリストを表示する。assets フォルダにテキストファイルで管理

Importerでtitle/telopの文字判定を行い位置を切り替える

**Comment by kwiksher** [comment]
キャプションのフレーム サイズですが、Scriptでは変更方法が見つかりませんでした。読み込んでいる TTMLのほうでサイズを指定しても無視されてしまいます。

TTMLから SRTに変更して試してみますので、もう少し時間がかかりそうです。

※TTMLで読み込んだCaptionのクリップのMotionデータのPositionなら変更できるのかもしれない （未調査）

**Comment by kwiksher** [comment]
SRT形式にすると Captionsの一覧なります。Import Settingsで予め設定された場所に読み込むことができます。しかし Scriptでの位置の切り替え方法は 見つかりませんでした。

![image](https://user-images.githubusercontent.com/4041539/79683168-09711300-8263-11ea-94b5-318815de1c72.png)

ImporterのAs Titlesは、mogrtで張り付けてます。なので中央に配置したいタイトルだけ Captionsから外して、mogrtで張り付けると動作にしようかと思います。As Titlesのボタンは無くして、チェックボックスにしてしまう。「title は中央」というチェックボックスが有効だと  絵コンテのCharacterのパラミターがtitleの場合に、 .mogrtで中央に配置する という仕様でどうでしょうか？

チェックボックスが無効だと そのまま 特別の扱いはせずに、全てCaptions （SRT読み込み）。

※ テロップ（telop)は和製英語なので、日本だけで通じます。

**Comment by usk-fujikawa** [comment]
「title は中央」というチェックボックスが有効だと 絵コンテのCharacterのパラミターがtitleの場合に、 .mogrtで中央に配置するという仕様で良いかと思います！

 テロップ（telop)ではなく、海外でも分かるようにするにはText（テキスト）とかがいいでしょうか？

**Comment by kwiksher** [comment]
XD Editor 0.4.1, Pr Importer 0.4.0 をアップしました。

Windows Prmiere 14.1 と　Mac 14.0.0 で動作することは確認しました。

CharacterにTitleという文字列があって、Importerのチェックボックスが有効だと　SbE_Title.mogrtを使って、配置してます。mogrtのテキスト設定を変えれば色々できるでしょう。

[SbE_Title.mogrt.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4509838/SbE_Title.mogrt.zip)

キャプションの方は　読み込む前に 読み込み設定をしておけば それが有効になります。
[Adobe Pr キャプションの操作
](https://helpx.adobe.com/jp/premiere-pro/using/working-with-captions.html)


XD Editor Captionが字幕にあたるのでCaptionもCharacterのSelect optionに入れておきましたが、それで動作は変わるということはありません。


<img width="1209" alt="2020-04-21_2047" src="https://user-images.githubusercontent.com/4041539/79862985-ee90d100-8411-11ea-9d6c-56021ebebcab.png">

**Comment by usk-fujikawa** [comment]
Prでエクスポートしたデータを読み込みました。

・Use Title mogrt チェックありの場合
下記のエラーが発生し、テキストが読み込まれない

<img width="1020" alt="スクリーンショット 2020-04-25 15 17 23" src="https://user-images.githubusercontent.com/47027471/80272921-b981c880-8708-11ea-8e48-62c8f187f11e.png">

・Use Title mogrt チェック無しの場合
テキストを設定していない箇所に[ : ]のテキストボックスが作成されてしまいます。

<img width="1999" alt="スクリーンショット 2020-04-25 15 20 00" src="https://user-images.githubusercontent.com/47027471/80272942-e03fff00-8708-11ea-9fc6-a31768122ba0.png">

エクスポートしたデータを添付します
[Bear_Walk.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4532476/Bear_Walk.zip)

**Comment by kwiksher** [comment]
Importer 0.4.1 をアップロードしました

空のストリングの対応と .md ":"
 でCharacterとTextを結合していた部分を削除。

※ CharacterやCommentも表示したいでしょうか？　マーカーを挿入させればいいかなぁと思ってます。

**Comment by usk-fujikawa** [comment]
動作確認しました

・Use Title mogrt チェックありの場合
まだ上記のエラーが発生してテキストが表示されません。
山本さんの方ではテキスト表示されていますでしょうか？

・Use Title mogrt チェック無しの場合
正常にテキストが表示されました。
CharacterやComment は表示せず、このままで問題ないかと思います。

**Comment by kwiksher** [comment]
Mac Pr 14.0 ですが、そちらは 14.1?  

After Effectは入ってますか？ mogrtって必要だったかもしれない。だけど以前は動いていたんですよね？ となると今回の修正が影響している。

**Comment by usk-fujikawa** [comment]
こちらもMac Pr 14.0になります。

Aeも入っています。
Use Title mogrtの対応が入ってから、Prの読み込みテストしたのは今回が初です。

**Comment by kwiksher** [comment]
環境の違いとして 一つ思いました。 .mogrtを予め Prのライブラリに登録して置かないと スクリプトでタイムラインに挿入できないのかも。添付のzipの中のSbE_Title.mogortをローカルライブラリに入れてみたらどうでしょう？

![image](https://user-images.githubusercontent.com/4041539/80304646-4bb1cb80-87f2-11ea-92ab-84fd58035059.png)
[SbE_Title.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4535097/SbE_Title.zip)

**Comment by usk-fujikawa** [comment]
原因が分かりました。

まず、私の方が映像の作業でVer 13.0が自動的起動していて、
Ver 14.0で読み込み直したら表示することができました。

Prのバージョンが異なるとSbE_Title.mogortの読み込みでエラーになってしまうようです。

Pr、Aeは他のプラグインの対応もあり、最新版を使っていないユーザーも多いです。

**Comment by usk-fujikawa** [comment]
他にも気がついた箇所があったので、
どうすると一番ユーザーが使いやすいのか、
他の講師と相談してまとめます。

**Comment by usk-fujikawa** [comment]
Ver 14.0でUse Title mogrtにチェックを入れてPrに読み込むと
タイトル部分のテキストが全て「Title」と表示されてしまい、
XDから書き出したテキストが正しく表示されていないようです。

<img width="2606" alt="スクリーンショット 2020-04-27 17 45 09" src="https://user-images.githubusercontent.com/47027471/80352696-39499780-88af-11ea-9f3f-4f705d48fe45.png">

エクスポートしたデータを添付します。
[Bear_Walk2.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4538441/Bear_Walk2.zip)

また、過去のバージョンのAeでmogrtでタイトルを作成すれば、
昔のバージョンのPrでもエラーにならず、起動できる事も確認できました。

**Comment by kwiksher** [comment]
こちらでは出てきました。Source Text のテキストフィールドの値がTitleのままでしょうか？
![image](https://user-images.githubusercontent.com/4041539/80375443-49736e00-88d3-11ea-96cd-475c52f0df4d.png)

**Comment by usk-fujikawa** [comment]
テキスト部分をクリックすると、一瞬タイトルのテキストが表示されますが、
すぐにテキストボックスからテキストが消滅してしまいます。

何か他に設定など必要でしょうか？

動画を添付します。

[Prテキスト.mp4.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4543191/Pr.mp4.zip)

**Comment by kwiksher** [comment]
昨日のZoomの結果として、.mogrtは外しました。

Importer 0.4.2 
Editor 0.4.5 

Markdownで改行ありの時のバグを修正しました。

**Comment by usk-fujikawa** [comment]
動作確認しましたが、Cut 1のテキストがない場合、Prに読み込んだ際にそれ以降のテキストがずれてしまう現象が発生しています。
md、jsonどちらの場合も発生しています。

<img width="2606" alt="スクリーンショット 2020-04-29 16 57 08" src="https://user-images.githubusercontent.com/47027471/80573589-31b6f980-8a3b-11ea-8c39-1abc9d335c6a.png">

プロジェクトファイルとエクスポートしたファイルを添付します。
[storyboard_インストール.xd.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4550415/storyboard_.xd.zip)

[SbE_Install.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4550419/SbE_Install.zip)

**Comment by kwiksher** [comment]
0.4.3 impoterで修正しました

スキップした時の startポジションがゼロのままでした。

**Comment by usk-fujikawa** [comment]
修正を確認しました！

Importerの仕様・動作はこれでOKだと思います。
