### ISSUE TITLE
Webサイトの運用について

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#31]
Webサイトの運用についてデジハリのWebや動画の先生から色々アドバイスをもらいました。

通常Ae、Pr映像のプラグインの販売を元に説明すると、

例：Element3D
国内：紹介サイト、チュートリアル、機能概要
https://flashbackj.com/product/element-3d

海外：開発元、販売
https://www.videocopilot.net/products/element2/

のように国内向けの紹介サイトと海外の開発向けのサイトに分かれている事が多いです。

私の方で国内（デジハリなど）向けに機能紹介やチュートリアルをアップするサイトも作成してみました。（作成中）
https://usk-sub.jimdofree.com

国内（デジハリなど）に向けての機能の紹介やセミナー情報は私のサイトで作成して、
発信していけばWebの更新もすぐにできますし、
ライセンスの販売や作成した絵コンテのアップについてはstoryboard.inkで切り分けたらどうかなと思いました。
どうでしょうか？

**Comment by kwiksher** [comment]
それで良いです。藤川さんブランドの方が影響力あると思います。storyboard.ink のほうからも　そちらに飛べるようにします。

**Comment by usk-fujikawa** [comment]
Webで使用している画像をアップロードしましたので、そちらのサイトで必要なものは使ってください。
https://drive.google.com/drive/folders/18Bt65MIRY8dJgA_tglyrQbcF_fx5nOjy?usp=sharing

**Comment by kwiksher** [comment]
ありがとうございます。

※ちょっと ネオスやらAI RCカーがらみの作業で Importerのほうが進んでませんが、今週末から来週前半にXML, MGRTの作業を行う予定です。
