### ISSUE TITLE
デジハリ フィードバック XD

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#33]
XDで新しいStoryboardを作成した際に、
添付の画像のように、header、tableのレイヤーをロックしてしまう事は可能か？

編集中に誤まってズレてしまったりしないので、ロックされていた方がいい

<img width="1684" alt="スクリーンショット 2020-04-21 15 11 43" src="https://user-images.githubusercontent.com/47027471/79832197-e15ced80-83e3-11ea-873c-12680d6fcf83.png">

XDでStoryboardを作成した際に、添付の画像のように絵コンテ分の枠を作成する事は可能か？
枠で各Cutが区切られていた方が見やすい。

<img width="1583" alt="スクリーンショット 2020-04-21 15 18 00" src="https://user-images.githubusercontent.com/47027471/79832358-37ca2c00-83e4-11ea-95b9-101a30e4df2c.png">

**Comment by kwiksher** [comment]
header, table.headerのほうは masterのArtboardのほうでロックを掛けておけば それが反映されます。

枠のほうですが RepeatGridの作成APIに以下の問題があり 難航中。

https://adobexdplatform.com/plugin-docs/reference/scenegraph.html#repeatgrid

- It is not currently possible for plugins to create a new RepeatGrid 
- duplicate commandをpluginで実行して ページの複製を行えば RepeatGridもコピーされる。

予め materのほうに RepeatGridを作っておけば良さそうですが、現在 RepeatGridに種別を変えてしますと、現在のコードのmasterのTable.rowの参照ができなくなってしまって、表作成がエラーになってしまいます。RepeatGridのオブジェクトの参照について、調査中です。

**Comment by kwiksher** [comment]
RepeatGridの行を増やしたり、パディングを変更は 現在 できません。ReadOnlyでした。

check boxを入れて 自動罫線 On/OFFにして　OFFの人は　自分でリビートグリッドにして、ONは枠を作る。

siteのstoryboard_template_*.xdのファイルは headerと table.hearder table.rowのメンバをロックにしておきました。

![image](https://user-images.githubusercontent.com/4041539/79945502-d91ab600-84a8-11ea-9890-28263be205e3.png)

**Comment by kwiksher** [comment]
0.4.2 で table.row を行数分 作成するようにしてしました。(repeatGrid使いたいオプションは後日）

※table.row 自体をロックすると複製できないのでメンバのnodeだけをロックしてます。

![image](https://user-images.githubusercontent.com/4041539/79983058-2e26ee00-84e2-11ea-8164-d8044de8b11e.png)

**Comment by usk-fujikawa** [comment]
枠が出来たのでかなり見やすくなったかと思います。

昨日は一日デジハリメンバーとZOOMでしたので、出てきた意見をまとめました。
下記対応可能でしょうか？

<img width="1641" alt="スクリーンショット 2020-04-23 1 13 50" src="https://user-images.githubusercontent.com/47027471/80049996-69abd180-854f-11ea-9a47-1081c864a231.png">

・Cut
最大20までになったので、２桁まで表示として、フォントサイズ：100にすると見やすい

・Time
こちらもTotalで1時間を超える事はなさそうなので,mm:ss:msecまでの表示とし、
フォントサイズ：80にすると見やすい
（可能ならテキストもセンター合わせ）

・Comment
コメントについては撮影スケジュールや、役者の動きなどかなり文章が長くなることがあるので、
長いとCut2のComment欄のように文章がはみ出してしまうため、テキストボックスを上段に合わせる。
（Textについてもコメントに合わせて上段合わせで良いかと思います。）

※テキストボックスを上段に合わせて配置すると、クリックした際にCut1の部分がアクティブになるので何処を編集しているかわかり易くなります。

プロジェクトファイルを添付します。
[storyboard_template_0423.xd.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4519807/storyboard_template_0423.xd.zip)

**Comment by kwiksher** [comment]
0.4.3 

![image](https://user-images.githubusercontent.com/4041539/80068035-dd62d400-8579-11ea-86ac-1c80ac410c89.png)

TimeのTotal からhh:を削るのは ちょっと 影響範囲が他にもあるのでそのままです。

Cutの方は２桁にしましたが、この数字は 出力する画像ファイルの名前のIndexとかに使っています。桁数に依存するところは Importerとかで なかったはずです、、多分だいじょうぶ

**Comment by usk-fujikawa** [comment]
確認しました。
修正ありがとうございます。
