### ISSUE TITLE
Storyboard Plugin ManagerのGifのRecと再生について

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#34]
ManagerでGifをRecした場合、Gifのループ形式が無限になっていないので、
Webなどに貼った場合、一度しか再生されなくなっています。
[storyboard1.gif.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4519818/storyboard1.gif.zip)

こちらは書き出す際にGifのループ形式を無限にする事は可能でしょうか？

<img width="1090" alt="スクリーンショット 2020-04-22 22 06 26" src="https://user-images.githubusercontent.com/47027471/80050802-982aac00-8551-11ea-9039-8b0d9d349523.png">

また、絵コンテを再生しようとして「Preview」、ファイルを選択せずに「キャンセル」
Managerの「Close」を押すと、アプリが落ちてしまいます。

<img width="1225" alt="スクリーンショット 2020-04-23 10 56 08" src="https://user-images.githubusercontent.com/47027471/80051024-18e9a800-8552-11ea-9ae0-4f3d7877ff99.png">

<img width="1225" alt="スクリーンショット 2020-04-23 10 56 12" src="https://user-images.githubusercontent.com/47027471/80051038-2141e300-8552-11ea-98cd-89f090f32e34.png">

**Comment by kwiksher** [comment]
0.4.2

runtime errorの修正
Loopするしないの選択ダイアログを追加しました。

![image](https://user-images.githubusercontent.com/4041539/80070826-93c8b800-857e-11ea-9a77-ac017a44d8f3.png)

**Comment by usk-fujikawa** [comment]
修正を確認しました。

キャンセルした際に、宇宙っぽい背景が出てくるので、次に修正する際に背景を白に直してもらえると良いかと思います。

<img width="1225" alt="スクリーンショット 2020-04-23 10 56 08" src="https://user-images.githubusercontent.com/47027471/80074559-52d3a200-8584-11ea-898e-629834e2842f.png">

あと、絵コンテを再生する際、映像は16:9が基本となるため、
Managerを起動した際のアプリのサイズが1280×720とかで起動するとよいかなと思いました。

GifをRecする際のサイズも Managerの表示サイズに依存するので、
デフォルト起動：1280×720で、ボタンで1920×1080にサイズ切り替えなど出来ればベストかと思います。

**Comment by kwiksher** [comment]
Manager 0.4.3 サイトからDLできます。

- 背景を白
- ライセンス切れで自動更新に失敗したら、Unistallしますか Dialog
- デファオルトサイズを1280x720, 最小を640x360 にしました。最大サイズやサイズをアプリのボタンで変更することは、APIがないのでできません。

**Comment by usk-fujikawa** [comment]
修正確認しました。
