### ISSUE TITLE
絵コンテ作成で途中でタイトルなどのテキストを表示する場合

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#36]
添付した画像のように、Cutの途中でタイトルのみのテキストを表示した場合、
前のCutの画像が残ってしまうため、
選択しているRowの部分に画像が挿入されてしまいます。

<img width="1448" alt="スクリーンショット 2020-04-24 16 26 22" src="https://user-images.githubusercontent.com/47027471/80186488-069e6580-8649-11ea-818e-7f0d0d779467.png">

[Update]ボタンを押した際に、Graphic欄の画像を消すか、
Graphic欄の画像を消す「Clear」ボタンなどが必要かと思います。

**Comment by kwiksher** [comment]
そうそう、それで Clear Buttonをプロパティの画像を空にするだけにしたんでした。

**Comment by usk-fujikawa** [comment]
修正確認しました。
