### ISSUE TITLE
Storyboard Editor、Manager、Importerの機能要望

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#37]
Storyboard Editor、Manager、Importerの機能要望について皆さんの意見をまとめました。
機能的に可能かどうかなど、明日お話し出来ればと思います。

Storyboard Editor XD 

添付した画像のように、[Update]ボタンを押した際に、Imageの欄にTitleやCaptionのテキスト内容を、テキストボックスを作成して表示できないか。（テキストサイズ：100）
テキストの内容が表示されると、映像の完成形がイメージしやすい。

[Character]のテキストもサイズ:80だと見やすい

<img width="1561" alt="スクリーンショット 2020-04-27 14 31 20" src="https://user-images.githubusercontent.com/47027471/80337167-342b1f00-8894-11ea-9b95-ea9cc98fc0d0.png">

書き出しの際に、cut 01-reference...の画像のみに、TitleやCaptionのテキストを乗せた状態で書き出す事は可能か。
テキストも合成されていれば、managerで再生した際も、TitleやCaptionがよりイメージし易い。

<img width="1213" alt="スクリーンショット 2020-04-27 14 44 18" src="https://user-images.githubusercontent.com/47027471/80337751-a05a5280-8895-11ea-9e5c-f25cd92cd50b.png">

Pr（Importer）

こちら色々な意見がありましたが、mogrtをあまり使用していない方も多く、
２種類のテキストが混在するのが分かりに難いので、当初の下部にテロップのように表示する形で統一し、タイトルの場合は手動でセンターに合わせる仕様でいいのでは、
という方が多かったです。
タイトルはロゴ画像などを仕様する事もあり、とにかくテロップをPrで作成するのが大変なので、
自動でテキスト作成できる方がありがたい。

**Comment by usk-fujikawa** [comment]
[Export As Markdown] のボタンですが、
mdとstoryboarderも出力するので、
シンプルに[Export] ボタンでいいかなと思いました。

<img width="336" alt="スクリーンショット 2020-04-29 17 10 16" src="https://user-images.githubusercontent.com/47027471/80574368-a76f9500-8a3c-11ea-8236-0d7cee2d0627.png">

**Comment by kwiksher** [comment]
Editor 0.5.0 
   Export As Markdown を Exportだけに修正 

残タスク
　 Caption Text を画像にOverlapか合成
　 PreviewでCaptionを表示しない　(画像にあるので)

**Comment by usk-fujikawa** [comment]
残タスク
　 Caption Text を画像にOverlapか合成
　 PreviewでCaptionを表示しない　(画像にあるので)

上記の修正の際にManagerの黒いバー部分を、Captionを抜いた分、高さを縮めてもらえると、
Caption Text を合成した画像部分も見えて良いかなと思います。

![スクリーンショット-2020-05-04-22 38 28](https://user-images.githubusercontent.com/47027471/80972370-feb89f80-8e58-11ea-8de3-f4891a5b7125.jpg)

**Comment by kwiksher** [comment]
Manager 0.5.1 Preview 
* Control ボックスの高さを小さくした
* Sliderのインジケータの形を四角に変更
* CaptionのテキストをConrol ボックスの外に出した
* キーボードの数字キーを押すとテキストの色が変わります。

XD Editor
* textOverを各テンプレートに追加 Sb Inkのサイトにアップした。
    * https://storyboard.ink/download/
* textOverは絵コンテの画像にTextを表示
* characterのフォントサイズを変更

<img width="721" alt="2020-05-05_1442" src="https://user-images.githubusercontent.com/4041539/81065413-5ec14b80-8f16-11ea-96fc-7921e254b096.png">

reference xx .pngの画像に文字は埋め込んでません。表示的にオバーレイにしただけです。なので markdown ファイルの方の画像には テロップの文字はオバーレイで出てきません。ManagerでA-GIFの方は変更はないので 文字は出ます。

**Comment by usk-fujikawa** [comment]
textOverの動作を確認した、Bugと要望をまとめました。

Bug
Cut 02以降のテキストが正しくtextOver されない

Cut 01では正しくtextOverされますが、 Cut 02 ではテキストが上部の位置にテキストが表示され、
Cut 03 以降ではテキストが表示されないようです。

<img width="2089" alt="スクリーンショット 2020-05-06 11 05 33" src="https://user-images.githubusercontent.com/47027471/81133441-a387c980-8f8c-11ea-8276-9dc43ee88bd3.png">


修正要望
・テロップ（Caption）が１行しか表示されない

テロップが２行になる際にテキストボックスの高さが小さく、１行しか表示されません。
テキストボックスの高さを広げるか、テキストボックスを作成する際に「ポイントテキスト」で作成できないか。
※ポイントテキストなら、自動で入力したテキストボックスの大きさになるようです。
テロップは２行まで想定しておいた方がいいかと思います。

<img width="1704" alt="スクリーンショット 2020-05-06 11 09 07" src="https://user-images.githubusercontent.com/47027471/81133651-3b85b300-8f8d-11ea-9a27-5c96602beb65.png">

<img width="1975" alt="スクリーンショット 2020-05-06 11 09 37" src="https://user-images.githubusercontent.com/47027471/81133757-90292e00-8f8d-11ea-9e5e-b9a165ddd5d3.png">



・タイトルをセンターに表示できないか

Titleに設定した場合に、テキストボックスの位置を移動してセンターに表示できないか。
もしくは、Title、Caption用のテキストを用意しておく。
絵コンテをクライアントに見せる際に、タイトルはセンターで表示できると良い。
※Ae、Pr読込みは下の位置のままでOK

<img width="1971" alt="スクリーンショット 2020-05-06 11 12 04" src="https://user-images.githubusercontent.com/47027471/81134226-12662200-8f8f-11ea-9071-012426ff9477.png">



・Manager

テロップ（Caption）のフォントサイズが大きく、テキストがはみ出しているので、
もう少し小さいサイズでいいかと思います。
こちらも、テロップが２行の場合も想定した方がよさそうです。
※２行になった場合は下の段のテロップは、黒いバーに被っても構わない

<img width="1115" alt="スクリーンショット 2020-05-06 11 13 46" src="https://user-images.githubusercontent.com/47027471/81134214-08dcba00-8f8f-11ea-92b4-e8966fd49500.png">

**Comment by kwiksher** [comment]
0.5.2 manager を Sb Inkサイトにアップしました。
* fontSize 変更
* textOptionで幅を指定 と自動改行
    * Corona SDKの制限で現在 行間の幅は指定できない
* Titleのときはセンターに、それ以外はコントロールボックスの上に。

0.5.2 Editor
* textOverが一行目以外の場所がNGだったのを修正
* Titleのときにセンターに、Title以外にしたら元に戻す

**Comment by usk-fujikawa** [comment]
動作確認しました。
これで問題ないかと思います。
