### ISSUE TITLE
Bug: Storyboard Plugin Manager の不具合

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#39]
Manager起動し、メニューが表示される前に、Previewから動画を再生すると、
動画に、バージョン情報が重なって表示される現象が起こります。

動画をアップロードしました
https://drive.google.com/file/d/1nDOcND21T9iE8maFgoiieC34Z8yn7wpO/view?usp=sharing

あと、前回のお話ししました、Rec時の再生バーが右側に突き抜けてしまう現象も合わせて修正お願いします。
<img width="1115" alt="スクリーンショット 2020-05-01 18 11 49" src="https://user-images.githubusercontent.com/47027471/80856977-7afc8880-8c89-11ea-98b5-885b56b77add.png">

**Comment by kwiksher** [comment]
Manager 0.5.0 を サイトにアップしました

   version 情報をサイトから取ってきているうちにPreviewされないようにしました。
　再生のスライダーの値が間違っていたので、修正してみました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。
