### ISSUE TITLE
Storyboard Editor  フィードバック UIデザインについて

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#40]
昨日、現状の機能についてデジハリのメンバーなどに紹介してみましたが、機能については評判もよく、いい感触でした。
少しUIなどのデザインに意見を頂いたので、こちらを修正できれば完璧かと思います。

・Storyboard Editor XD

Cut、Time、Characterの表示位置を下記の画像のようにセンターに表示する。

<img width="1907" alt="スクリーンショット 2020-05-08 19 25 57" src="https://user-images.githubusercontent.com/47027471/81461758-f362cc80-91e8-11ea-834b-1e90b53f8943.png">

・Manager

ImageMagickのテキストが紫のバーに被っているので、画像のようにPreviewの下部に配置するとデザイン的にスッキリする

![Manager_画面2](https://user-images.githubusercontent.com/47027471/81461860-81d74e00-91e9-11ea-9c9a-d88a510af7b7.png)

　
　
Preview時のアイコンを画像のように綺麗に並べて配置する

![Manager_画面](https://user-images.githubusercontent.com/47027471/81461880-b77c3700-91e9-11ea-8b61-6ad1afe08260.png)

**Comment by kwiksher** [comment]
Manager 0.6.0
Editor 0.6.0 をアップロードしました。

**Comment by usk-fujikawa** [comment]
確認しました。

Preview時のアイコンの方は対応できそうでしょうか？
アイコンがSVGの方が良ければ作成して送ります

**Comment by kwiksher** [comment]
あれ ManagerのPreviewのアイコン入れましたけど、出てません？
アイコンはちなみにイメージシートのシートになってます。

[controls.psd.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4605612/controls.psd.zip)

**Comment by usk-fujikawa** [comment]
こちらのPCではこのように位置や大きさがズレて表示されていますが、
そちらは正しく表示されていますでしょうか？

<img width="1213" alt="スクリーンショット 2020-05-10 21 39 30" src="https://user-images.githubusercontent.com/47027471/81499494-0966af00-9307-11ea-8bb1-99df24b1291c.png">

**Comment by kwiksher** [comment]
わかりました。サイズとアラインを全部同じにしたいのですね。timeとtotal timeのフォントも同じにしておきます。

**Comment by kwiksher** [comment]
0.6.1 maanger アップロードしました

![image](https://user-images.githubusercontent.com/4041539/81523858-255f6480-938a-11ea-9f9d-02741ca06075.png)

**Comment by usk-fujikawa** [comment]
修正確認しました。
対応ありがとうございます。
