### ISSUE TITLE
Bug:２つ以上の絵コンテを作成して読み込むとPr、Aeで読込みエラーが発生

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#41]
2個以上のアートボードで絵コンテを作成し、エクスポートすると、
2個目の.md のファイル名が summary.md になっており、こちらをPr、Aeに読み込むとエラーが発生します。

※１つ目の storyboard1.md は正常に読み込めている
また .storyboderのファイルについてはどちらも正常に読み込めております。

<img width="995" alt="スクリーンショット 2020-05-10 12 03 45" src="https://user-images.githubusercontent.com/47027471/81489929-52424780-92b6-11ea-99e7-735c2d3f37c6.png">

プロジェクトとエクスポートしたファイルを添付しました
https://drive.google.com/drive/folders/1SxOXwzH_NQDtZ_dMkvCv-I9FdajA2xPf?usp=sharing

**Comment by kwiksher** [comment]
複数あった場合に　XDの出力を summary.mdにまとめていたので、個別に storyboard1.md, storyboard2.mdと出力するようにします。

**Comment by usk-fujikawa** [comment]
個別に storyboard1.md, storyboard2.mdと出力する方式で良いかと思います。
宜しくお願いします。

**Comment by kwiksher** [comment]
Editor 0.6.1 md ファイルを個別に出力をアップロードしました

**Comment by usk-fujikawa** [comment]
動作確認しましたが、以下のような不具合が発生します。

PrにStoryboard1、Storyboard2を連続してインポートすると、

最初にインポートしたテキスト1の文章が、2番目にインポートしたテキストにも同じ文書1が入ってきてしまいます。
※画像は正しくStoryboard1、Storyboard2のものがインポートされています。


<img width="2606" alt="スクリーンショット 2020-05-12 13 10 05" src="https://user-images.githubusercontent.com/47027471/81638126-1db7c280-9453-11ea-981d-0d1d6c9cb237.png">


<img width="2606" alt="スクリーンショット 2020-05-12 13 10 19" src="https://user-images.githubusercontent.com/47027471/81638148-2a3c1b00-9453-11ea-9cc4-c30876866ea8.png">

エクスポートしたファイルを添付します
https://drive.google.com/drive/folders/1D5DUry9UIJ2CCXDLwGK-Vxd7XryVY-57?usp=sharing

**Comment by kwiksher** [comment]
コードで今 itemのbin(フォルダ）がstoryboardと固定値デ、captions.srt（固定名）で入れてるからと思われます。

storyboard1, storyboar2   としようと思います。シーケンスのseq00も固定値なので、これも seq_storyboard1 とします？ （多分可能）

**Comment by usk-fujikawa** [comment]
storyboard1, storyboar2とし、シーケンスもseq_storyboard1、seq_storyboard2で作成して頂ければと思います。

**Comment by kwiksher** [comment]
Importer 0.6.0 をアップしました {name}に絵コンテのnameをセットしました。
  Pr seq_{name}
  Ae comp_{name}

**Comment by usk-fujikawa** [comment]
動作確認しましたが、
seq_storyboard1、seq_storyboard2でシークエンスは作成されましたが、
まだ、seq_storyboard2 内のテキストに seq_storyboard1 のテキストの内容が表示されております。

再現動画を添付します。
https://drive.google.com/file/d/1N-C_AWF33clhop4SyEGlvbtjvh64ZtdL/view?usp=sharing

**Comment by kwiksher** [comment]
Importer 0.6.1 をアップしました。

.md ファイルは 個別のフォルダに格納されていないので、生成される captions.srtが上書きされてました。
.mdの時は、storyboard1.srt, storyboard2.srtの絵コンテの名前をつけました。

.storyboarerの時は、フォルダに格納されているので そのまま captions.srtです。

**Comment by usk-fujikawa** [comment]
Pr、Ae共に正常に動作することを確認しました。
対応ありがとうございました。
