### ISSUE TITLE
Bug:複数のストリーボードがある状態で削除すると.md ファイルが出力されない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#42]
正常ルートでの絵コンテ作成・読み込みについてはほぼ大丈夫そうです。

正常ルート以外の動作確認もしていますが、
XDで複数のStoryboardを作成後、Exportの select allで全てのボードにチェックが入っている状態で、
1個のStoryboardを丸ごと削除した後にエクスポートを押すと、
.mdファイルのみが出力されない現象が起こりました。

※ Storyboardを丸ごと削除する前に、select allで全てのボードチェックを外して削除すれば、
Export した際に.mdファイルも出力されています。

再現動画を添付します。
https://drive.google.com/file/d/1a3XWHMHg0UtLpodfWwl0w_unPNpKX5AS/view?usp=sharing

プロジェクトファイル
[TEST3.xd.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4621043/TEST3.xd.zip)

**Comment by kwiksher** [comment]
Editor 0.6.2 をアップしました。

artboard nameチェックとスキップをいれました。

**Comment by usk-fujikawa** [comment]
修正を確認しましたが、下記の現象が発生する用になってしまいました。

チェックボックスにチェックが入っていない場合も「Export」ボタンが押せる用になってしまう。

再現手順を録画しました。
https://drive.google.com/file/d/1f7QkIzGsKCHMPAmfzVJoSdtplX7Sfpge/view?usp=sharing

**Comment by usk-fujikawa** [comment]
あと、こちらの現象も発生しました。

ストーリーボード削除後に「All Select」・チェックボタンが効かなくなってします。

再現手順動画
https://drive.google.com/file/d/1Km41vghIKeN6v3yIpO3NUuXqV9xPEL3O/view?usp=sharing

**Comment by kwiksher** [comment]
0.6.3 Editor をアップロードしました。

checkbox のv-modelの初期化をartboardの削除が発生したときに入れました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。

全て正常に動作することを確認しました。
