### ISSUE TITLE
Bug : Storyboard EditorのRemoveとAdd使用した際の表示

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#43]
Storyboard EditorのRemoveとAdd使用した際に以下の現象が発生しました。

・Remove
絵コンテの中の1CutをRemoveすると、Cut番号などは正しく表示されるが、
Total Timeの表示が、Remove前と同じになっている。
※他のCutでUpdateを押すとTimeは再計算される。

再現動画
https://drive.google.com/file/d/1UmGSq6zzTy0laDXDsLyQOIAz3RPtbiGa/view?usp=sharing

・Add
AddでCutを追加した際に、Tittleを選んでいても、Undefinedと表示され、
Imageの欄にテキストが中央ではなく、Captionの位置に表示されてします。

再現動画
https://drive.google.com/file/d/1YIlVgrAGXDCotAr_VlHOWibpRl9DtK-A/view?usp=sharing

プロジェクトも添付します。
[TEST3.xd.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4654929/TEST3.xd.zip)

**Comment by kwiksher** [comment]
0.6.4 Editor をアップロードしました。

Remove 削除対象の時間も足していたので、足さないように修正
Add     character を参照するように修正。Titleの時にtextOver位置を中央にする

**Comment by usk-fujikawa** [comment]
全て修正されていることを確認しました。
