### ISSUE TITLE
Bug : Storyboard Editorでメニューが表示されない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#44]
XDを最新バージョン(29.1.32.8)にアップデートしたところ、メニューが表示されなくなる現象が発生しております。
再現動画をお送りします。

https://drive.google.com/file/d/1O1fx-MnACV5YPsXQGhicoz5rg0uq6gtv/view?usp=sharing

私のMacBook Proでは上記のの現象が発生しておりますが、
生徒の動作確認ではCreateボタンを押しても絵コンテが作成されず、何も反応しないようです。
※XDのは同様の最新バージョン(29.1.32.8)

**Comment by usk-fujikawa** [comment]
追記
どちらもMac OSです。

過去に作成したプロジェクトファイルだとメニューが表示されるが、
最新のテンプレートで一から作成しようとすると、メニューが表示されません。
※再現率100%

**Comment by usk-fujikawa** [comment]
原因がわかりました。
私が使用している、Macbook Proの方に「Meiryo Bold」が入っていなかったのが原因のようです。
テンプレートのフォントをArialに変更したら、メニューが表示されるようになりました。

<img width="1557" alt="スクリーンショット 2020-05-29 16 17 28" src="https://user-images.githubusercontent.com/47027471/83232525-487e7680-a1c8-11ea-8ed0-6b0db393e4ac.png">

修正したテンプレート
[テンプレート0529.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4700232/0529.zip)

テンプレートのフォントをどのOSにもあるフォントに変更した方が良さそうです。

**Comment by kwiksher** [comment]
頂いた修正テンプレートを Sb Inkにアップしておきました
