### ISSUE TITLE
Bug: Animateへの読み込みでテキストが正しく表示されない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#45]
Animate を20.0.3にアップデートしたところ、画像は正しく読み込めるようになりましたが、
１番最初のテキストが全てカットに表示されるようになっているようです。

再現動画
https://drive.google.com/file/d/1dI904BExzhPmXTbM3F_CyTfPklb5QjPD/view?usp=sharing

**Comment by kwiksher** [comment]
各テキストは dialogue レイヤーのアクショスクリプトで設定されています。

caption02.source.text = " Good Morning ";

シンボルで一括調整とかしたいかと思いまして、シンボルでテキストを配置したためです。



https://storyboard.ink/doc/get_started/img/2020-06-14-16-49-34.png

**Comment by usk-fujikawa** [comment]
パブリッシュして再生しましたが、シンボルに正しくテキストが読み込めれていないようです。

再現動画
https://drive.google.com/file/d/1_oL6Uto_x14OuMbOQdx-5KWUAcy2EuVL/view?usp=sharing

また、ユーザーの視点だとアクショスクリプトで設定されてしまうと、タイムライン上で内容が確認できなくなってしますので、かなり不便に感じるように思います。
内容を確認する際に、再生しないといけないので長編の動画の場合はかなり大変そうです。

個人的にはPrやAeのようにcharacterレイヤー上にテキストボックスを作成して、テキストを読み込めると使いやすいかと思います。

**Comment by kwiksher** [comment]
わかりました、それでは それぞれ シンボルにしましょう。

テキストが出てこないのは フォント埋め込みの設定かなと思います。

**Comment by usk-fujikawa** [comment]
それぞれ シンボルしてもらえると、ユーザーも使い易いかと思います。

よろしくお願い致します。

**Comment by kwiksher** [comment]
Importer 1.0.2 

JSFL スタティックテキストにして それぞれシンボルにしました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。

読み込み自体はこれで良いかと思いますが、下記のケースの対応策が必要そうです。

絵コンテが複数の場合でAnにインポートする場合
１つの.mdファイル自体は問題なく読み込めますが、
Cutが20以上あり複数の.mdファイルをインポートしようとすると、
シンボル名が同じになってしまい添付画像のようにメッセージが表示されます。
（カット数分メッセージが出るので消すのも大変です）

Anについてはアニメでの使用が想定されますが、
実写物の映像と比べて、アニメの方が絵コンテ数が多い傾向があるので、
対応策が必要かと思います。

Pr、Aeのようにそれぞれの絵コンテを
１シンボル（ムービークリップ）で作成していく

<img width="1920" alt="スクリーンショット 2020-06-17 12 05 06" src="https://user-images.githubusercontent.com/47027471/84852385-a8659000-b097-11ea-9f37-f556a058744b.png">

**Comment by kwiksher** [comment]
importer 1.0.3  JSFL インポートした 画像と作成したCaption シンボルは、ライブラリで フォルダに入れるようにしました。フォルダ名は .md .storybarderのファイル名です。

**Comment by usk-fujikawa** [comment]
Animateを最新版にアップデートしてテストしたところ、
読み込んだテキストが縦に表示されるようになってしまいました。
原因わかりますでしょうか。

<img width="2672" alt="スクリーンショット 2020-06-21 14 18 38" src="https://user-images.githubusercontent.com/47027471/85217313-622b6c00-b3ca-11ea-8432-9b9818b6b0fc.png">

flaファイルを添付します。
[test_0621.fla.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4808945/test_0621.fla.zip)

**Comment by kwiksher** [comment]
importer 1.0.4 をアップしました。

公開された 20.5 ですが、setTextRectangle()も 使わないと幅が指定されたものにならないようです。

**Comment by usk-fujikawa** [comment]
テキストの修正を確認しました。
正常にテキストを表示できました。

また、複数の絵コンテを読み込んだ場合に、上書きのメッセージは表示されなくなりましたが、
2個以上読み込んだ場合に、添付の画像のように同じタイムラインに展開されてしまうので、
ユーザーがかなり見難いように感じました。

添付したflaファイル(test_0621B)のようにStoryboardごとにシンボル（グラフィック）を作成し、
その中に展開するのは難しいでしょうか？
添付のファイルのように展開可能なら、複数の絵コンテを読み込んだ場合もかなり使い易いように思います。

処理的に難しいそうでしたら、チュートリアルでシンボルを作成後にimporterで読み込む使い方にすれば、運用でカバーすることも可能です。

<img width="2672" alt="スクリーンショット 2020-06-21 16 38 48" src="https://user-images.githubusercontent.com/47027471/85219638-aaee1f80-b3e0-11ea-914e-a95255221332.png">

flaファイル
[test_0621B.fla.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4809081/test_0621B.fla.zip)

**Comment by kwiksher** [comment]
シンボル化しておきます。

※シーンに分けて 運用してもらうか、ユーザがシンボル化するかなとおもってました。

**Comment by usk-fujikawa** [comment]
シンボル化する際にシンボルを（グラフィック）で作成してもらえると見やすくなるかと思います。
※ムービークリップで作成してしまうとタイムラインで確認し難いです。

**Comment by kwiksher** [comment]
Importer 1.0.5 をアップロードしました。

FIX JSFL a storyboard is now a graphic symbol

**Comment by usk-fujikawa** [comment]
修正を確認しました。

これで完璧だと思います。
