### ISSUE TITLE
絵コンテに後からAddボタンでCutで追加した場合、絵コンテの下部の枠が切れてしまう

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#46]
絵コンテに後からAddボタンでCutで追加した場合、絵コンテの下部の枠が切れてしまいます。

実際に運用した場合、後からAddでCut数を増やすケースが多そうです。

・絵コンテを作成
<img width="2395" alt="スクリーンショット 2020-09-06 12 25 42" src="https://user-images.githubusercontent.com/47027471/92317687-b562a180-f03e-11ea-9e56-cbf8dfc65885.png">

・後からAddでCutを追加
<img width="2395" alt="スクリーンショット 2020-09-06 12 26 30" src="https://user-images.githubusercontent.com/47027471/92317732-1ee2b000-f03f-11ea-8a12-398f67f014a8.png">

**Comment by kwiksher** [comment]
table/row を追加する処理

**Comment by usk-fujikawa** [comment]
修正を確認しました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。
