### ISSUE TITLE
Characterのテキストボックスに直接テキスト入力してしまうケースがある

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#47]
Characterのコンボボックスの下部のテキストボックスに直接テキストを入力してしまい。
間違う人が何名かいました。

現状ではTittleかCaptionのみですので、
コンボボックスの（TittleかCaption）が反映され、テキストボックスに直接入力できないようにすることは可能でしょうか。

<img width="2395" alt="スクリーンショット 2020-09-06 12 51 07" src="https://user-images.githubusercontent.com/47027471/92317882-96650f00-f040-11ea-9b75-a8cb8792401d.png">

<img width="2395" alt="スクリーンショット 2020-09-06 12 51 13" src="https://user-images.githubusercontent.com/47027471/92317886-9f55e080-f040-11ea-81a5-b7541848bdde.png">

**Comment by kwiksher** [comment]
デジハリ 仕様で そういうCharacterの入力ボックスを なくしてしまうことは可能です。Configファイルを追加して それで切り替え。

Ttilte/Captionではなく 普通にキャラクター名を入れたい ユーザのほうが 多いような気がするので、テキスト入力ボックスは残しておきたい。Storyboarderや  FadeInやFountainの脚本でも Character（人物）とDialog（会話）が基本なので。

**Comment by usk-fujikawa** [comment]
こちらは現状のままで問題なさそうです。
