### ISSUE TITLE
絵コンテをブラウザで共有した際のトップ画面について

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#49]
絵コンテをXDで共有した場合に下記のURLのように元の空欄のテンプレートが表示されます
https://xd.adobe.com/view/9d8f69b5-761c-4352-8fb1-ec9ad5a16634-c8dc/

チュートリアルやセミナーでは右▶︎キーを押すと絵コンテが表示されますと解説していますが、
実際に運用が始まると、初めてURLが送られてきたクライアントなどは困るかなと感じました。

どのような改善点方法があるか？

・テンプレートに「Enter 右▶︎キー」みたいなテキストを表示する。
　（最初に絵コンテを作成する際にテンプレートに「Enter 右▶︎キー」と書いてあるのが不自然）

・オートで２枚目のシートに動くようにプロトタイプで設定する
　（現状プロトタイプにWriteはできない）

<img width="1953" alt="スクリーンショット 2020-09-07 19 40 49" src="https://user-images.githubusercontent.com/47027471/92379216-0dce9780-f142-11ea-851d-ac48ef0b3f27.png">

**Comment by kwiksher** [comment]
プラグインにモードを追加
* Editモードで テンプレートを表示 
* 閲覧モードで テンプレートを非表示

テンプレートと絵コンテのアートボードの順番を変えて、テンプレートを最後にしてみたら どうだろうか。

単純に 共有するときには、マニュアルで削除では 駄目なのか？

**Comment by kwiksher** [comment]
プロトタイプ 画面で 対象のアートボードだけを 選択して 、プレビュー ＞ シェア で  OKでした。

**Comment by kwiksher** [comment]
template.xdを使わずに 始めてしまうユーザ対策も含めて、テンプレートを表示しない、値を内部にもつ。
サイズ指定 
- 1280*720
- 1920*1080 

template artboardを開くと 使える機能があるので、template が開いていないときの対処も必要

**Comment by usk-fujikawa** [comment]
こんなUIにしたらどうかと思いますが如何でしょうか。
コンボボックスコンボボックスで（1920×1080 or 1280×720）を選択

![SbE_UI](https://user-images.githubusercontent.com/47027471/92716749-2f29c080-f39a-11ea-96a9-a1505747a0f7.jpg)

**Comment by usk-fujikawa** [comment]
ボード作成位置ですが現状のこちらの配置から、添付画像のように配置可能でしょうか。

もし下記のように左上から配置可能でしたら、Cut数の最大値も20から40に引き上げてもらえると、
Cut数の多い場合でも対応できるので、さらに便利になるかと思います。

・現状
<img width="2583" alt="スクリーンショット 2020-09-12 12 49 55" src="https://user-images.githubusercontent.com/47027471/92986612-34e8e880-f4f7-11ea-8781-6c4f6f4776e0.png">


・修正案
<img width="2583" alt="スクリーンショット 2020-09-12 12 52 37" src="https://user-images.githubusercontent.com/47027471/92986618-403c1400-f4f7-11ea-934a-ab82d7c3707c.png">

**Comment by kwiksher** [comment]
![image](https://user-images.githubusercontent.com/4041539/92988110-adee3d00-f503-11ea-9840-bf6aa384ca70.png)

XDでファイルを開くときに Custom Sizeを選択すると Canvasが開く。Artboardは空。

それ以外は Artboardが新規作成されます。そのArtboardは デフォルトの場所。この左上にないアートボードが 空だったら、削除してしまう。 空でない場合は  左上に 移動させてから、新規に絵コンテアートボードを作成する。

**Comment by usk-fujikawa** [comment]
確かに、テンプレートを使用しないと、何かデフォルトのプロジェクトを選ぶので、
Customsize以外はアートボードが出てきてしまいますね。

基本的にチュートリアルではCustom Sizeを選択して解説していく方がいいでしょうか？

**Comment by kwiksher** [comment]
画像ファイルをドラッグして　絵コンテに配置する場合と　手書きのワークシートをリポートグリッドで指定して インポートする場合は、任意のアートボードを利用するようにしました。

添付のZIPの中の STORYBOARD_EDITOR_DEV を　下記のフォルダに入れて　一通りテストをお願いします。

~/Library/Application Support/Adobe/Adobe XD/develop/

- バージョン番号は変更してません。

- SelectionとExport以外の機能全てが 影響範囲です。

- 既存の template.xd を利用して master アートボードが存在する場合は  master の要素を参照するようにしてあります。masterというアートボード名があるとそれを参照します。

※ パネルのImage Size 1920x1080、1280x720 を参照してます。編集時に スイッチはNGです。現在　この状態を XD ファイル毎に保存してはいません。メタデータに保存して、固定・不変に 一両日に対応します。

[STORYBOARD_EDITOR_DEV_0914.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/5216851/STORYBOARD_EDITOR_DEV_0914.zip)

**Comment by usk-fujikawa** [comment]
ダウンロードして動作確認をしてみました。
使用していて気になる点をまとめました。

１・Createした際の絵コンテの位置が左側にずれる
アートボード位置が添付の画像用に左側にめり込んでしまいます。

<img width="2583" alt="スクリーンショット 2020-09-14 18 01 12" src="https://user-images.githubusercontent.com/47027471/93066913-82ab4f80-f6b5-11ea-9340-61b73faf962f.png">


２・Createした際にアートボードの表示が外面のセンターのままなので、
アートボード新しく作成されたのが分かり難い。一見何もできて内容に思えてしまう
また、画面の左側に移動するのが大変。

- 絵コンテのアートボードを作成した際に、表示場所を移動できないか？
- 以前のように中心に絵コンテを作成した方が良いのか？

<img width="2583" alt="スクリーンショット 2020-09-14 18 01 25" src="https://user-images.githubusercontent.com/47027471/93067203-e170c900-f6b5-11ea-8cb3-156e8e98d791.png">


3・エクスポートした際にライセンスが認証されていないようになる。
現状のテスト版ではエクスポート負荷でしょうか？

<img width="441" alt="スクリーンショット 2020-09-14 18 07 24" src="https://user-images.githubusercontent.com/47027471/93067564-56440300-f6b6-11ea-9f52-83a189148aa2.png">


４・1つのCut内容を入力し、Updateを押した後に、そのCutの行がアクティブでなくなるので、
▶︎ボタンを押しても次の行に移動できない。

- 毎回入力したい行を選択する必要があるのか

<img width="2583" alt="スクリーンショット 2020-09-14 18 16 38" src="https://user-images.githubusercontent.com/47027471/93067912-c3579880-f6b6-11ea-9d2f-b09445742778.png">

**Comment by usk-fujikawa** [comment]
絵コンテが左側に見切れて作成されてしまう現象の原因が分かりました。

XDのスケールを2.5%にして、全てのアートボードの範囲が表示されている状態で、
絵コンテをCreateボタンを押すと正常な位置に絵コンテが作成されますが、
XDのスケールが50%ぐらいで、アートボード全体が表示されていない状態で、
Createボタンを押すと、絵コンテが左側に食い込んだ状態で作成されてしまうようです。

・XDのスケールを2.5%でCreateした場合
<img width="2583" alt="スクリーンショット 2020-09-15 0 05 25" src="https://user-images.githubusercontent.com/47027471/93103530-b8692c00-f6e7-11ea-8838-72fc136d8b8a.png">


・XDのスケールを50%でCreateした場合（作成後に2.5%で表示）
<img width="2583" alt="スクリーンショット 2020-09-14 18 01 12" src="https://user-images.githubusercontent.com/47027471/93103665-e189bc80-f6e7-11ea-842a-cc80540ad9fd.png">

**Comment by usk-fujikawa** [comment]
PCによって画面の解像度も違う思いますが、
スケールを2%ぐらいにして全体が表示可能か？

絵コンテのCreate時に「選択範囲に合わせてズーム」できないか？

<img width="643" alt="スクリーンショット 2020-09-15 0 21 10" src="https://user-images.githubusercontent.com/47027471/93104970-77721700-f6e9-11ea-8e3a-d92053c91691.png">

**Comment by kwiksher** [comment]
０９１５版を添付しました。入れ替えてみてください。バージョン番号はそのままです。

[STORYBOARD_EDITOR_DEV_0915.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/5221953/STORYBOARD_EDITOR_DEV_0915.zip)

＞１・Createした際の絵コンテの位置が左側にずれる
＞２・Createした際にアートボードの表示が外面のセンターのままなので、

viewport APIを使ってみました。
https://adobexdplatform.com/plugin-docs/reference/viewport.html

＞3・エクスポートした際にライセンスが認証されていないようになる。

正式版の プラグインのファルダの中の assets フォルダの kwkcontrol.regを DEVの方にも入れれば　動作するはずです。 

＞４・1つのCut内容を入力し、Updateを押した後に、そのCutの行がアクティブでなくなるので、

アクティブになるように修正してみました。

**Comment by usk-fujikawa** [comment]
修正を確認しました。
全体的にとても使用しやすくなったかと思います。

正常ルートは問題なさそうですので、
引き続き、色々なケースの動作確認を行ってみます。
