### ISSUE TITLE
Bug: Browseからの画像の読み込みでpngしか選択できない

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#6]
Browseから画像を選択する際に、pngのみでjpegなどが選択できない。
※ドラッグ＆ドロップの場合はjpegも取り込める

<img width="1750" alt="スクリーンショット 2020-01-07 14 37 41" src="https://user-images.githubusercontent.com/47027471/71871110-7ef51f80-315b-11ea-80e7-bc1bc66165b3.png">

**Comment by usk-fujikawa** [comment]
拡張子が.jpgは選択できるが、.jpegの場合が選択できない

<img width="1277" alt="スクリーンショット 2020-01-21 19 25 37" src="https://user-images.githubusercontent.com/47027471/72797114-e47cfc00-3c83-11ea-951e-826468758c08.png">

**Comment by kwiksher** [comment]
file dialogの設定に png, jpg, jpegの文字列を指定してみました

**Comment by usk-fujikawa** [comment]
修正を確認しました
