### ISSUE TITLE
Bug:エクスポートしたデータを Premiereに読み込むとタイムラインの時間が異なる

### ISSUE THREAD

**Issue by usk-fujikawa** [kwiksher/storyboard-editor-plugin#7]
エクスポートしたデータをPremiereに読み込んだ際に、Storyboard Editorで設定した時間とPremiereに読み込まれた時間が異なる

<img width="759" alt="スクリーンショット 2020-01-06 21 22 15" src="https://user-images.githubusercontent.com/47027471/71871553-d47dfc00-315c-11ea-917e-670d5951637b.png">

<img width="1585" alt="スクリーンショット 2020-01-06 21 22 46" src="https://user-images.githubusercontent.com/47027471/71871560-dcd63700-315c-11ea-8691-606c6c28c6c7.png">

**Comment by kwiksher** [comment]
//	(e.g. 10.5 is 10 seconds, 5 frames) or in timecode ('00;00;10;05').

という仕様らしい

**Comment by kwiksher** [comment]
mm:hh.msec への表記に合わせて CEP importerをアップデート

**Comment by usk-fujikawa** [comment]
エクスポートしたデータをPrに読み込んだ際に、
タイムラインの最初の0〜1秒（画像の赤枠部分）に画像やテキストが表示されず、
１秒以降から映像が始まるようになっている

<img width="2415" alt="スクリーンショット 2020-01-24 17 21 08" src="https://user-images.githubusercontent.com/47027471/73054621-3d3fd500-3ece-11ea-8bca-285e942e2257.png">

**Comment by kwiksher** [comment]
最初のカットの終了時間から setInPointしていた部分を修正してみました。

**Comment by usk-fujikawa** [comment]
エクスポートしたデータを読み込むと、テキストボックスも作成されず、画像も最初の１枚のみしか表示されなくなりました。
※どのデータでも再現する

<img width="1542" alt="スクリーンショット 2020-02-12 0 12 47" src="https://user-images.githubusercontent.com/47027471/74249488-9318d780-4d2c-11ea-8033-d668fdab58b4.png">

**Comment by kwiksher** [comment]
![image](https://user-images.githubusercontent.com/4041539/74311196-39f38700-4db2-11ea-91fd-21a777e439da.png)

Timeの表示ですが、MDファイルでは 下記になってましたか？
`
  00:01.000
  total
  00:00:01.000  
`

**Comment by usk-fujikawa** [comment]
MDファイルTimeは正しいようです。
テストでXDからエクスポートしたデータも添付します。

本日修正したバージョン219.12.13だとテキストは表示されましたが、画像が表示されず、また最初の1秒も空欄になっています。

[storyboard.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4190622/storyboard.zip)

[storyboard_001.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4190624/storyboard_001.zip)



<img width="1966" alt="スクリーンショット 2020-02-12 17 14 09" src="https://user-images.githubusercontent.com/47027471/74315857-b6d72e80-4dbb-11ea-891f-8cfa186a0b5d.png">

**Comment by kwiksher** [comment]
＞バージョン219.12.13
postmanでのバージョン番号が古いままでしたね。

 こちら（Windows )だと再現しないんですよねー。importerのアップデートがうまくいってないのかも知れません。明日、importerが立ち上がったら、バージョンがでるようにしてみます。

＞テストでXDからエクスポートしたデータ

念のため確認ですが、これって以前のバージョンのプラグインのexport 機能があったときのものですよね？

**Comment by usk-fujikawa** [comment]
新しいテンプレートで再度データをエクスポートして、
Prに読み込もうとしましたが、エクスポート時にエラーが発生します。

<img width="1129" alt="スクリーンショット 2020-02-13 11 00 23" src="https://user-images.githubusercontent.com/47027471/74394728-ba68c500-4e50-11ea-991c-e3b6fc12d403.png">

エクスポートしたデータも添付します。
[storyboard1.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4196126/storyboard1.zip)

Prに添付したデータを読み込んだ状態のキャプチャーです。
画像は全て表示されますが、テキストがCut5のみしか表示されず、タイムラインも異なっています。

<img width="1966" alt="スクリーンショット 2020-02-13 11 02 48" src="https://user-images.githubusercontent.com/47027471/74394924-4a0e7380-4e51-11ea-8841-7c883358b9f0.png">

**Comment by kwiksher** [comment]
＞エクスポートしたデータも添付します。
＞storyboard1.zip 

をもらいましたが、export すると mdファイルになるはずなのですが、なぜ storyboarder のファイルなのでしょうか？ storyboardderのファイルのエクスポートは 今のpluginではされないはずなのですが、、、。

で premiere でインポートするときは、mdファイルではなくて、.storyboarder のをインポートしているということでしょうか？XDのファイルそのものが欲しいです。

USK
   Mac版の方は今まで.storyboarderしかエクスポートされた事ないです。
   エクスポートしてもmdファイルが出力されません。

  IMacの方がアップデート後にライセンスの認証エラーが出てエクスポートできない状態です。

   iMac
   1/7バージョンからのアップデート

＝＞
    アップデートならば、DB上はそのまま使えるはずだけど、何かおかしい？ > ymmt

**Comment by usk-fujikawa** [comment]
先日インストールのテストで使用した奥さんのMacで一から動作確認を行いました。
エクスポート時に下記のエラーが発生し、mdファイル自体が作成されないことが原因のようです。
[.sotryborder]ファイルが生成されている。

Mac版では今まで一度もmdファイルが生成できていなかった。

<img width="441" alt="スクリーンショット 2020-02-14 11 05 22" src="https://user-images.githubusercontent.com/47027471/74495240-8fe33e80-4f1a-11ea-827c-e87cf9128bcb.png">

プロジェクトファイルとエクスポートしたファイルも添付します。

[test.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4202338/test.zip)

**Comment by kwiksher** [comment]
0215版をアップロードしました。バージョン番号が manager, plugin, importer extensionに表示されます。下記ページにスクリーンショットを貼っておきました。

   https://kwiksher.com/storyboard-editor/doc/installation/

サーバのライセンス修正をしましたので、一度 manager appから Show License > Transfer Licenseでライセンスの消去をお願いします。消去後に manager appを再起動して、アクティベーションを行ってください。

![image](https://user-images.githubusercontent.com/4041539/74582789-a618f980-5003-11ea-85c4-8bd862d096e1.png)

※XD pluginのほうでは .storyboarderは出力しないようにしました。ライセンスOKならば、mdファイルがサーバで生成されて保存されます。

**Comment by usk-fujikawa** [comment]
ライセンスを入れ替えて、XDからmdファイルが出力されることが確認できました。

Prに読み込んだ際に、画像のタイムラインは全てあっていますが、
テキストの４つ目のタイムラインが短くなっていました。

<img width="1966" alt="スクリーンショット 2020-02-15 22 40 47" src="https://user-images.githubusercontent.com/47027471/74589001-ca48fa80-5044-11ea-82aa-19a1ca6e86e2.png">

プロジェクトファイル等を添付します。
[Storyboard_Editor_XD.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4208529/Storyboard_Editor_XD.zip)

**Comment by usk-fujikawa** [comment]
何度か動作確認を行いましたが、
エクスポートしたデータをPrに読み込んだ際に、最後のテキストのタイムラインの秒数が異なってします様です。（XDのデータよりも長い場合と短い場合がある）
※画像のタイムラインは合っており、テキストのみにズレが発生

<img width="2606" alt="スクリーンショット 2020-02-16 18 15 39" src="https://user-images.githubusercontent.com/47027471/74602128-06359b80-50e9-11ea-97de-eccfc37c2dde.png">

こちらのテストデータも添付しておきます。
[Storyboard_Editor_XD_0216.zip](https://github.com/kwiksher/storyboard-editor-plugin/files/4209574/Storyboard_Editor_XD_0216.zip)

**Comment by kwiksher** [comment]
Fixed in 0.1.1 最後のフレームの長さの修正

**Comment by usk-fujikawa** [comment]
Prに正しいタイムラインでエクスポートしたデータを読み込めることを確認しました。
